import kotlin.String

/**
 * Generated by [gradle-kotlin-dsl-libs](https://github.com/jmfayard/gradle-kotlin-dsl-libs)
 *
 * Run again
 *   `$ ./gradlew syncLibs`
 * to update this file */
object Libs {
    /**
     * [webextensions-declarations website](https://github.com/cypressious/kotlin-webextensions-declarations) */
    const val webextensions_declarations: String =
            "com.github.cypressious.kotlin-webextensions-declarations:webextensions-declarations:" + Versions.webextensions_declarations

    const val com_gradle_build_scan_gradle_plugin: String =
            "com.gradle.build-scan:com.gradle.build-scan.gradle.plugin:" + Versions.com_gradle_build_scan_gradle_plugin

    const val jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin: String =
            "jmfayard.github.io.gradle-kotlin-dsl-libs:jmfayard.github.io.gradle-kotlin-dsl-libs.gradle.plugin:" + Versions.jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin

    /**
     * [kotlin-gradle-plugin website](https://kotlinlang.org/) */
    const val kotlin_gradle_plugin: String =
            "org.jetbrains.kotlin:kotlin-gradle-plugin:" + Versions.org_jetbrains_kotlin

    /**
     * [kotlin-stdlib-js website](https://kotlinlang.org/) */
    const val kotlin_stdlib_js: String =
            "org.jetbrains.kotlin:kotlin-stdlib-js:" + Versions.org_jetbrains_kotlin
}
